### PR TITLE
Escape xml characters in filter.xml

### PR DESCRIPTION
**Pull request by dnlek**
It breaks output XML

### CODE REVIEW

**Comment by alexkli** [comment]
Thanks for the patch! I guess there are some other chars not handled properly yet either.

* Do you have a test case or sample steps to reproduce?
* The escaping/stripping of the package name is happening [here](https://github.com/Adobe-Marketing-Cloud/tools/blob/master/repo/repo#L630-L631), that would be a better place to get rid of the ampersand and other breaking and weird looking characters for the pkgName, which is just for informational purposes anyway
* `filesystem_to_jcr` does the same mappings that jackrabbit filevault is doing, but the XML encoding in the filter.xml is a separate thing (i.e. `&` is a valid char in JCR), so I'd move the escaping for the filter.xml inside `create_pkg_meta_inf` right where it writes it to XML, to keep things clearly separated for future changes

**Comment by dnlek** [comment]
Hi @alexkli 
From package xmls there are normally 5 illegal characters: `&<>'"`
I've extended my patch to escape all of them.

ad1. test case scenario is to run put operation on file `a&<>~`!@$^&()'b.html` which will produce corrupted AEM package (xml will be invalid)

ad2. We could escape package name at the very beginning but we can't remove those characters from filter.xml - then need to stay there but escaped. This is why I decided to escape both in the same way in `create_pkg_meta_inf`. This patch is only related to invalid xmls not invalid characters in package name in general

ad3. So I've extracted xml escaping into separate function and escape anything that will come to `create_pkg_meta_inf`. for sake of completeness we could also escape other attributes here.

**Comment by alexkli** [comment]
Thanks. Will incorporate.

I found that `<>` is getting percent-escaped as `%3c%3e` by filevault (in the filenames within the zip), thus creating separate files and breaking `get, st, diff` for the `a&<>~``!@$^&()'b.html` example file after the filter.xml encoding is fixed. Code seems to be [PlatformNameFormat.java](https://github.com/apache/jackrabbit-filevault/blob/0dcf09d58fa40cbe3bc24dcb6a00281123bd5a1c/vault-core/src/main/java/org/apache/jackrabbit/vault/util/PlatformNameFormat.java#L75), which also does that for few other characters. Seeing if that can be handled.

**Comment by alexkli** [comment]
Well, it's ok to live with the %3c encoding on the file system - that's how vault will check it out or what a simple unzip will do.

However, even doing
1. a `repo get` of a folder containing `a&<>~``!@$^&()'b.html`
2. which will store it on the FS (osx) as `a&%3c%3e~``!@$^&()'b.html`
3. followed by a `repo st a\&%3c%3e~\``\!@\$\^\&\(\)\'b.html` (shell escaping reached via bash-completion)
4. will result in a mismatch:

```
diff: REMOTE/tmp/test/a&%3c%3e~`!@$^&()'b.html: No such file or directory
```

(Note the single backtick in the filename gets messed up by markdown here, they end up being duplicated)

**Comment by alexkli** [comment]
The problem is that putting the percent-escaped path in the filter.xml (for the `repo st` to download the server version to compare to), will create an empty package. The filter path must be unescaped aka the raw JCR path (xml escaped within the filter.xml serialization).

**Comment by alexkli** [comment]
@dnlek Again, thanks for the fix!  Merged and fixed the url decoding plus some minor adjustments in https://github.com/Adobe-Marketing-Cloud/tools/commit/4f9a40de0544367994eb90c30069ece5b0c69ca6

Please try the latest master version.

**Comment by dnlek** [comment]
@alexkli Thanks, your changes looks good! I used ampersand escape because when I created package in crxde it was escaped this way.

**Comment by alexkli** [comment]
@dnlek Ampersand xml entity escape is still necessary for xml and I haven't changed it.

The percent escaping is something that filevault does [here](https://github.com/apache/jackrabbit-filevault/blob/0dcf09d58fa40cbe3bc24dcb6a00281123bd5a1c/vault-core/src/main/java/org/apache/jackrabbit/vault/util/PlatformNameFormat.java#L93-L103) when it maps a JCR path to a filename for the file entries in a zip and thus for a vault checkout. It's not doing that for the filter.xml entries - these are strictly raw JCR paths (only xml escaped escaped).

When you create `a&<>~!@$^&()'b.html` in the JCR and then do a `repo get` (of the parent folder), you'll get the `<>` percent escaped as `%3c%3e` in the local filename. Then for future operations, such as `repo st <file>`, repo has to unescape that when it adds it to the filter.xml (before xml escaping).

I always knew there was more to this, but great to finally tackle this. There is one more thing left in terms of the "jcr:content" to "_jcr_content" namespace mapping, which repo just does hardcoded for a few known namespaces because it's much simpler. Filevault [handles it](https://github.com/apache/jackrabbit-filevault/blob/0dcf09d58fa40cbe3bc24dcb6a00281123bd5a1c/vault-core/src/main/java/org/apache/jackrabbit/vault/util/PlatformNameFormat.java#L20-L53) generically, but it's a bit tricky to do this in a shell script.

**Pull request merged**
