### PR TITLE
Add ability to 'put' package to both Author and Publish 

### PR DESCRIPTION
**Pull request by clanceyp**
Sometimes it's handy to push to Author and Publish simultaneously, e.g. when working on HTL or UI assets.

### CODE REVIEW

**Comment by alexkli** [comment]
Why not simply invoke this?

```
repo put && repo put -s publish:4503
```

I am hesitant to add such a change that only works for some commands (writing to server) and not others (reading - because it doesn‘t make sense there). It complicates the script logic for future maintenance. And what if you want to push to 3 or more instances, it would get more complicated than simple separate invocations.

**Comment by clanceyp** [comment]
That's an excellent idea, do you know how to configure IntelliJ to  run `repo put && repo put -s publish:4503` via the external tools dialog?
I've never had occasion to deploy to more than two instances, usually it's the author/publish run modes that need to be accommodated, for UI development one author and one publish instance is enough to check everything is working as expected.

**Comment by alexkli** [comment]
I don’t know if you can provide a shell command such as && in IntelliJ, but you can always have a small shell script here.

**Comment by clanceyp** [comment]
That's starting to sound a bit more complex, the publish URL parameter needs to be in the same place as the author one or they'll get out of step and the last thing you want to do is run a put to miss matched pair.

**Comment by alexkli** [comment]
You can have a shell script repoput.sh like

```
#!/bin/sh

repo put -s $1 && repo put -s $2
```

And in IntelliJ you then set the command to

```
repoput.sh localhost:4502 localhost:4503
```

**Comment by clanceyp** [comment]
For anyone else who needs the ability to 'put' to author and publish, here is a script that adds support for an optional `publish` param in the `.repo` properties file.

To implement;
* save the following script somewhere on your path e.g. `/usr/local/bin/repoput` 
* in your IDE integration settings locate the 'repo put' config and change `repo` to `repoput` (or whatever you called it) keeping all the other settings the same e.g. `repo put -f $FilePath$` => `repoput put -f $FilePath$`
* add the appropriate publish URL to the relevant `.repo` file e.g. `publish="http://localhost:4503"` 

``` #!/bin/bash

# use this bash script in conjunction with repo (https://github.com/Adobe-Marketing-Cloud/tools)
# to 'put' changes to both author and publish AEM instances

# default settings
# these values will be overwritten by the values set in .repo properties file
server="http://localhost:4502"
publish=

function abspath() {
    # generate absolute path from relative path
    # $1     : relative filename
    # return : absolute path
    if [ -d "$1" ]; then
        # dir
        echo "$(cd "$1"; pwd)"
    elif [ -f "$1" ]; then
        # file
        if [[ $1 == */* ]]; then
            echo "$(cd "${1%/*}"; pwd)/${1##*/}"
        else
            echo "$(pwd)/$1"
        fi
    fi
}

function find_up () {
    # find a file upwards in the tree
    # $1     : start directory
    # $2     : file to find in dir or any ancestor
    # return : found file or empty
    dir=$(abspath "$1")
    while [ -n "$dir" ]; do
        if [ -e "$dir/$2" ]; then
            echo "$dir/$2"
            break
        fi
        dir=${dir%/*}
    done
}

# get sever and publish settings from .repo file
repoCfg=$(find_up "$PWD" .repo)

if [ -f "$repoCfg" ]; then
    source "$repoCfg"
fi

repo $*

if [[ $1 == "put" && -n $publish ]]; then
    repo $* -s $publish
fi
```

**Pull request closed without merging**
